=== requiser/BB89VXXML/BB89VX_1008/1. feladat/BB89VX_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}/\d{2}_\d"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BME"/>
            <xs:enumeration value="ELTE"/>
            <xs:enumeration value="SZTE"/>
            <xs:enumeration value="ME"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen"/>
            <xs:enumeration value="nem"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato"/>
                <xs:element ref="kurzusok"/>
            </xs:sequence>
            <xs:attribute name="tanev" type="tanevTipus" use="required"/>
            <xs:attribute name="egyetem" type="egyetemTipus" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="hallgato" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hnev" type="xs:string"/>
                <xs:element name="szulev" type="xs:string"/>
                <xs:element name="szak">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="evf" type="xs:integer" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="kurzusok">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kurzus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="kurzus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzusnev" type="xs:string"/>
                <xs:element name="kredit" type="xs:integer"/>
                <xs:element name="hely" type="xs:string"/>
                <xs:element name="idopont">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nap" type="xs:string"/>
                            <xs:element name="tol" type="xs:string"/>
                            <xs:element name="ig" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:choice>
                    <xs:element name="oktato" type="xs:string"/>
                    <xs:element name="oraado" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="idTipus" use="required"/>
            <xs:attribute name="jovahagyas" type="igenNemTipus" use="optional"/>
            <xs:attribute name="nyelv" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== requiser/BB89VXXML/BB89VX_1015/2. feladat/BB89VX_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<kurzusfelvetel tanev="2024/25_1" egyetem="ME" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BB89VX_kurzusfelvetel.xsd">
    <hallgato>
        <hnev>Szabó Péter</hnev>
        <szulev>2002</szulev>
        <szak evf="3">Mérnökinformatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="ABC123">
            <kurzusnev>Adatbázis-kezelés</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/204</hely>
            <idopont>
                <nap>Hétfő</nap>
                <tol>10:00</tol>
                <ig>12:00</ig>
            </idopont>
            <oktato>Dr. Kovács László</oktato>
        </kurzus>

        <kurzus id="DEF456" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Programozás I.</kurzusnev>
            <kredit>6</kredit>
            <hely>Inf/101</hely>
            <idopont>
                <nap>Kedd</nap>
                <tol>12:00</tol>
                <ig>14:00</ig>
            </idopont>
            <oktato>Dr. Nagy Éva</oktato>
        </kurzus>

        <kurzus id="GHI789">
            <kurzusnev>Hálózati technológiák</kurzusnev>
            <kredit>4</kredit>
            <hely>Inf/202</hely>
            <idopont>
                <nap>Szerda</nap>
                <tol>8:00</tol>
                <ig>10:00</ig>
            </idopont>
            <oraado>Dr. Kiss Béla</oraado>
        </kurzus>

        <kurzus id="JKL101" jovahagyas="igen" nyelv="angol">
            <kurzusnev>Szoftverfejlesztés</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/305</hely>
            <idopont>
                <nap>Csütörtök</nap>
                <tol>14:00</tol>
                <ig>16:00</ig>
            </idopont>
            <oktato>Dr. Horváth Márk</oktato>
        </kurzus>

        <kurzus id="MNO112">
            <kurzusnev>Algoritmusok és Adatszerkezetek</kurzusnev>
            <kredit>6</kredit>
            <hely>Inf/203</hely>
            <idopont>
                <nap>Péntek</nap>
                <tol>10:00</tol>
                <ig>12:00</ig>
            </idopont>
            <oraado>Dr. Balogh Anna</oraado>
        </kurzus>
    </kurzusok>
</kurzusfelvetel>
