=== requiser/BB89VXXML/XMLTaskBB89VX/XMLSchemaBB89VX.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Gyökér -->
    <xs:element name="allatmenhelyek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="varosok" type="VarosokTipus"/>
                <xs:element name="dolgozok" type="DolgozokTipus"/>
                <xs:element name="allatok" type="AllatokTipus"/>
                <xs:element name="menhelyek" type="MenhelyekTipus"/>
                <xs:element name="betegsegek" type="BetegsegekTipus"/>
                <xs:element name="orokbefogadok" type="OrokbefogadokTipus"/>
            </xs:sequence>
        </xs:complexType>

        <!-- Kulcsok -->
        <xs:key name="varosKulcs">
            <xs:selector xpath="varosok/varos"/>
            <xs:field xpath="@iranyitoszam"/>
        </xs:key>

        <xs:key name="menhelyKulcs">
            <xs:selector xpath="menhelyek/menhely"/>
            <xs:field xpath="@nyilvantartasi_azonosito"/>
        </xs:key>

        <xs:key name="dolgozoKulcs">
            <xs:selector xpath="dolgozok/dolgozo"/>
            <xs:field xpath="@szemelyi_szam"/>
        </xs:key>

        <xs:key name="orokbefogadoKulcs">
            <xs:selector xpath="orokbefogadok/orokbefogado"/>
            <xs:field xpath="@szemelyi_szam"/>
        </xs:key>
    </xs:element>

    <!-- Telefonszám típus -->
    <xs:simpleType name="TelefonszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="06[237]0[0-9]{7}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Irányítószám típus -->
    <xs:simpleType name="IranyitoszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Nem típus -->
    <xs:simpleType name="NemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Férfi"/>
            <xs:enumeration value="Nő"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Faj típus -->
    <xs:simpleType name="FajTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Kutya"/>
            <xs:enumeration value="Macska"/>
            <xs:enumeration value="Nyúl"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Címek típusa -->
    <xs:complexType name="CimTipus">
        <xs:sequence>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name="iranyitoszam" type="IranyitoszamTipus" use="required"/>
    </xs:complexType>

    <!-- Városok típusa -->
    <xs:complexType name="VarosokTipus">
        <xs:sequence>
            <xs:element name="varos" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="terulet" type="xs:float"/>
                        <xs:element name="lakossag" type="xs:positiveInteger"/>
                    </xs:sequence>
                    <xs:attribute name="iranyitoszam" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Dolgozók típusa -->
    <xs:complexType name="DolgozokTipus">
        <xs:sequence>
            <xs:element name="dolgozo" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="beosztas" type="xs:string"/>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="nem" type="NemTipus"/>
                        <xs:element name="edesanyja_leanykori_neve" type="xs:string"/>
                        <xs:element name="lakhely" type="CimTipus"/>
                        <xs:element name="telefonszam" type="TelefonszamTipus"/>
                    </xs:sequence>
                    <xs:attribute name="szemelyi_szam" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Állatok típusa -->
    <xs:complexType name="AllatokTipus">
        <xs:sequence>
            <xs:element name="allat" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="eletkor" type="xs:string"/>
                        <xs:element name="faj" type="FajTipus"/>
                    </xs:sequence>
                    <xs:attribute name="azonosito_kod" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Menhelyek típusa -->
    <xs:complexType name="MenhelyekTipus">
        <xs:sequence>
            <xs:element name="menhely" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="ferohely" type="xs:positiveInteger"/>
                        <xs:element name="telefonszam" type="TelefonszamTipus"/>
                        <xs:element name="cim" type="CimTipus"/>
                    </xs:sequence>
                    <xs:attribute name="nyilvantartasi_azonosito" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Betegségek típusa -->
    <xs:complexType name="BetegsegekTipus">
        <xs:sequence>
            <xs:element name="betegseg" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="gyogymod" type="xs:string"/>
                        <xs:element name="gyogyulasi_ido" type="xs:positiveInteger"/>
                        <xs:element name="tuntetek" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="latin_nev" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Örökbefogadók típusa -->
    <xs:complexType name="OrokbefogadokTipus">
        <xs:sequence>
            <xs:element name="orokbefogado" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="szul_ido" type="xs:string"/>
                        <xs:element name="telefonszam" type="TelefonszamTipus"/>
                        <xs:element name="lakhely" type="CimTipus"/>
                    </xs:sequence>
                    <xs:attribute name="szemelyi_szam" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Idegen kulcs kapcsolatok -->
    <xs:keyref name="dolgozoLakhelyRef" refer="varosKulcs">
        <xs:selector xpath="dolgozok/dolgozo/lakhely"/>
        <xs:field xpath="@iranyitoszam"/>
    </xs:keyref>

    <xs:keyref name="menhelyVarosRef" refer="varosKulcs">
        <xs:selector xpath="menhelyek/menhely/cim"/>
        <xs:field xpath="@iranyitoszam"/>
    </xs:keyref>

    <xs:keyref name="orokbefogadoLakhelyRef" refer="varosKulcs">
        <xs:selector xpath="orokbefogadok/orokbefogado/lakhely"/>
        <xs:field xpath="@iranyitoszam"/>
    </xs:keyref>
</xs:schema>

=== requiser/BB89VXXML/XMLTaskBB89VX/XMLBB89VX.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<allatmenhelyek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaBB89VX.xsd">
  <varosok>
    <varos iranyitoszam="4000,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,4011,4012,4013,4014,4015,4016,4017,4018,4019,4020,4021,4022,4023,4024,4025,4026,4027,4028,4029,4030,4031,4032,4063">
      <nev>Debrecen</nev>
      <terulet>461</terulet>
      <lakossag>201704</lakossag>
    </varos>
    <varos iranyitoszam="3300,3304">
      <nev>Eger</nev>
      <terulet>92</terulet>
      <lakossag>49499</lakossag>
    </varos>
    <varos iranyitoszam="3500,3501,3502,3503,3504,3505,3506,3507,3508,3509,3510,3511,3512,3513,3514,3515,3516,3517,3518,3519,3520,3521,3522,3523,3524,3525,3526,3527,3528,3529,3530,3531,3532,3533,3534,3535">
      <nev>Miskolc</nev>
      <terulet>236</terulet>
      <lakossag>143502</lakossag>
    </varos>
  </varosok>
  <dolgozok>
    <dolgozo szemelyi_szam="123456EE">
      <beosztas>Gondozó</beosztas>
      <nev>Kiss Béla</nev>
      <nem>Férfi</nem>
      <edesanyja_leanykori_neve>Dobó Beáta</edesanyja_leanykori_neve>
      <lakhely iranyitoszam="3515">
        <utca>Kossuth utca</utca>
        <hazszam>11</hazszam>
      </lakhely>
      <telefonszam>06301234567</telefonszam>
    </dolgozo>
    <dolgozo szemelyi_szam="234567RR">
      <beosztas>Állatorvos</beosztas>
      <nev>Nagy Béla</nev>
      <nem>Férfi</nem>
      <edesanyja_leanykori_neve>Kiss Margit</edesanyja_leanykori_neve>
      <lakhely iranyitoszam="3525">
        <utca>Petőfi utca</utca>
        <hazszam>12</hazszam>
      </lakhely>
      <telefonszam>06701234567</telefonszam>
    </dolgozo>
    <dolgozo szemelyi_szam="345678TT">
      <beosztas>Menedzser</beosztas>
      <nev>Lakatos Gizella</nev>
      <nem>Nő</nem>
      <edesanyja_leanykori_neve>Tóth Éva</edesanyja_leanykori_neve>
      <lakhely iranyitoszam="3515">
        <utca>Hunyadi utca</utca>
        <hazszam>1</hazszam>
      </lakhely>
      <telefonszam>06601234567</telefonszam>
    </dolgozo>
  </dolgozok>
  <allatok>
    <allat azonosito_kod="00001">
      <nev>Foltos</nev>
      <eletkor>1</eletkor>
      <faj>Kutya</faj>
    </allat>
    <allat azonosito_kod="00002">
      <nev>Cirmi</nev>
      <eletkor>3</eletkor>
      <faj>Macska</faj>
    </allat>
    <allat azonosito_kod="00003">
      <nev>Tappancs</nev>
      <eletkor>4 év</eletkor>
      <faj>Nyúl</faj>
    </allat>
  </allatok>
  <menhelyek>
    <menhely nyilvantartasi_azonosito="718293002">
      <nev>Miskolci Állatsegítő Alapítvány</nev>
      <ferohely>300</ferohely>
      <telefonszam>06701234501</telefonszam>
      <cim iranyitoszam="3529">
        <utca>Sajószigeti út</utca>
        <hazszam>23</hazszam>
      </cim>
    </menhely>
    <menhely nyilvantartasi_azonosito="553242112">
      <nev>Ebrendészeti Telep</nev>
      <ferohely>400</ferohely>
      <telefonszam>06701234502</telefonszam>
      <cim iranyitoszam="4002">
        <utca>Bánk</utca>
        <hazszam>72</hazszam>
      </cim>
    </menhely>
    <menhely nyilvantartasi_azonosito="620903992">
      <nev>Állatokat Védjük Együtt Alapítvány</nev>
      <ferohely>200</ferohely>
      <telefonszam>06701234503</telefonszam>
      <cim iranyitoszam="3300">
        <utca>Külterület</utca>
        <hazszam>1</hazszam>
      </cim>
    </menhely>
  </menhelyek>
  <betegsegek>
    <betegseg latin_nev="influenza_felis">
      <nev>Macska Influenza</nev>
      <gyogymod>Antibiotikumos kezelés</gyogymod>
      <gyogyulasi_ido>7</gyogyulasi_ido>
      <tuntetek>orrfolyás, tüsszögés</tuntetek>
    </betegseg>
    <betegseg latin_nev="canis_parvovirus">
      <nev>Parvovírus</nev>
      <gyogymod>Intravenás folyadékpótlás</gyogymod>
      <gyogyulasi_ido>6</gyogyulasi_ido>
      <tuntetek>hasmenés, hányás</tuntetek>
    </betegseg>
    <betegseg latin_nev="feline_infectious_peritonitis">
      <nev>Fertőző hashártyagyulladás(FIP)</nev>
      <gyogymod>Antibiotikumos kezelés</gyogymod>
      <gyogyulasi_ido>16</gyogyulasi_ido>
      <tuntetek>láz, levertség, fogyás, étvágytalanság</tuntetek>
    </betegseg>
    <betegseg latin_nev="myxomatosis">
      <nev>Myxomatosis</nev>
      <gyogymod>Védőoltás</gyogymod>
      <gyogyulasi_ido>14</gyogyulasi_ido>
      <tuntetek>bőr duzzanatok, étvágytalanság</tuntetek>
    </betegseg>
  </betegsegek>
  <orokbefogadok>
    <orokbefogado szemelyi_szam="987654AB">
      <nev>Horváth János</nev>
      <szul_ido>1992.11.02.</szul_ido>
      <telefonszam>06201234567</telefonszam>
      <lakhely iranyitoszam="3515">
        <utca>Béke utca</utca>
        <hazszam>5</hazszam>
      </lakhely>
    </orokbefogado>
    <orokbefogado szemelyi_szam="876543CD">
      <nev>Kovács Anna</nev>
      <szul_ido>1999.09.09.</szul_ido>
	  <telefonszam>06201234568</telefonszam>
	  <lakhely iranyitoszam="4001">
		  <utca>Tavasz utca</utca>
		  <hazszam>8</hazszam>
	  </lakhely>
	</orokbefogado>
	<orokbefogado szemelyi_szam="876543EF">
		<nev>Horváth Eszter</nev>
		<szul_ido>1990.12.01.</szul_ido>
		<telefonszam>06201234569</telefonszam>
		<lakhely iranyitoszam="3300">
			<utca>Nyár utca</utca>
			<hazszam>13</hazszam>
		</lakhely>
	</orokbefogado>
  </orokbefogadok>
</allatmenhelyek>
