=== requiser/BB89VXXML/BB89VX_0924/2. feladat/BB89VX_orarend.dtd
<!ELEMENT Szeman_Balazs_orarend (ora+)>
        <!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
        <!ATTLIST ora
                id ID #REQUIRED
                tipus (eloadas | gyakorlat) #REQUIRED>
        <!ELEMENT targy (#PCDATA)>
        <!ELEMENT idopont (nap, tol, ig)>
            <!ELEMENT nap (#PCDATA)>
            <!ELEMENT tol (#PCDATA)>
            <!ELEMENT ig (#PCDATA)>
        <!ELEMENT helyszin (#PCDATA)>
        <!ELEMENT oktato (#PCDATA)>
        <!ELEMENT szak (#PCDATA)>

=== requiser/BB89VXXML/BB89VX_0924/2. feladat/BB89VX_orarend_kulso.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Szeman_Balazs_orarend SYSTEM "BB89VX_orarend.dtd">
<Szeman_Balazs_orarend>
    <ora id="id_01" tipus="eloadas">
        <targy>Korszeru Informacios Technologiak</targy>
        <idopont>
            <nap>Hetfo</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Árvai László Lajos</oktato>
        <szak>Mernokinformatikus</szak>
    </ora>
    <ora id="id_02" tipus="gyakorlat">
        <targy>Korszeru Informacios Technologiak</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>Inf/15</helyszin>
        <oktato>Soós Róbert</oktato>
        <szak>Mernokinformatikus</szak>
    </ora>
    <ora id="id_03" tipus="eloadas">
        <targy>Oracle Rendszergazda</targy>
        <idopont>
            <nap>Hetfo</nap>
            <tol>08:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Dr. Kovács László József</oktato>
        <szak>Mernokinformatikus</szak>
    </ora>
    <ora id="id_04" tipus="gyakorlat">
        <targy>Oracle Rendszergazda</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>13:00</tol>
            <ig>15:00</ig>
        </idopont>
        <helyszin>Inf/202</helyszin>
        <oktato>Szűcs Miklós</oktato>
        <szak>Mernokinformatikus</szak>
    </ora>
    <ora id="id_05" tipus="eloadas">
        <targy>Adatkezeles XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Mernokinformatikus</szak>
    </ora>
    <ora id="id_06" tipus="gyakorlat">
        <targy>Adatkezeles XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Mernokinformatikus</szak>
    </ora>
</Szeman_Balazs_orarend>
